# MariaDB 기준 DDL

CREATE TABLE users (
    user_id       VARCHAR(50) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    name          VARCHAR(50) NOT NULL,
    password      VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE place (
    place_id      VARCHAR(20)  NOT NULL,
    title         VARCHAR(200) NOT NULL,
    addr1         VARCHAR(500),
    addr2         VARCHAR(500),
    mapx          VARCHAR(100) NOT NULL,
    mapy          VARCHAR(100) NOT NULL,
    first_image   VARCHAR(1000),
    like_count    INT(50)       DEFAULT 0,
    place_type    VARCHAR(20)  NOT NULL,
    lclssystm1    VARCHAR(100),
    lclssystm2    VARCHAR(100),
    lclssystm3    VARCHAR(100),
    CONSTRAINT pk_place PRIMARY KEY (place_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE MY_SCHEDULE (
    MY_SCHEDULE_ID    VARCHAR2(20)  NOT NULL,
    TITLE             VARCHAR2(200) NOT NULL,
    START_AT          DATE          NOT NULL,
    BUDGET_DETAILS    VARCHAR2(200),
    TODO_DETAILS      VARCHAR2(200),
    IS_SHARED         NUMBER(1)     DEFAULT 0,
    USER_ID           VARCHAR2(20)  NOT NULL,
    CONSTRAINT PK_MY_SCHEDULE PRIMARY KEY (MY_SCHEDULE_ID),
    CONSTRAINT FK_SCHEDULE_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE SCHEDULE_POST (
    POST_ID           VARCHAR2(20)  NOT NULL,
    TITLE             VARCHAR2(200) NOT NULL,
    LIKE_COUNT        NUMBER(20)    DEFAULT 0,
    VIEW_COUNT        NUMBER(20)    DEFAULT 0,
    BUDGET_DETAILS    VARCHAR2(200),
    TODO_DETAILS      VARCHAR2(200),
    POSTED_AT         DATE          NOT NULL,
    IS_ANONYMOUS      NUMBER(1)     NOT NULL,
    USER_ID           VARCHAR2(20)  NOT NULL,
    CONSTRAINT PK_POST PRIMARY KEY (POST_ID),
    CONSTRAINT FK_POST_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE VISIT_ITEM (
    VISIT_ITEM_ID     NUMBER(20)    NOT NULL,
    VISIT_ORDER       NUMBER(10)    NOT NULL,
    DISTANCE_TO_NEXT  NUMBER(20),
    PLACE_ID          VARCHAR2(20)  NOT NULL,
    SCHEDULE_ID       VARCHAR2(20)  NOT NULL,
    SCHEDULE_TYPE     VARCHAR2(20)  NOT NULL,
    CONSTRAINT PK_VISIT_ITEM PRIMARY KEY (VISIT_ITEM_ID),
    CONSTRAINT FK_VISIT_PLACE FOREIGN KEY (PLACE_ID) REFERENCES PLACE(PLACE_ID)
);

CREATE TABLE SCHEDULE_SHARE_USER (
    SHARE_ID          NUMBER(20)    NOT NULL,
    PERMISSION        VARCHAR2(10)  NOT NULL,
    MY_SCHEDULE_ID    VARCHAR2(20)  NOT NULL,
    SHARED_USER_ID    VARCHAR2(20)  NOT NULL,
    CONSTRAINT PK_SHARE PRIMARY KEY (SHARE_ID),
    CONSTRAINT FK_SHARE_SCHEDULE FOREIGN KEY (MY_SCHEDULE_ID) REFERENCES MY_SCHEDULE(MY_SCHEDULE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SHARE_USER FOREIGN KEY (SHARED_USER_ID) REFERENCES USERS(USER_ID)
);