package com.letsgo.place.model;

public interface MyScheduleQuery {
	String GET_MY_SCHEDULE_LIST_SQL = "SELECT s.MY_SCHEDULE_ID, s.TITLE AS SCH_TITLE, s.START_AT, s.IS_SHARED, p.TITLE AS PLACE_TITLE, p.ADDR1, p.FIRST_IMAGE FROM MY_SCHEDULE s JOIN VISIT_ITEM v ON s.MY_SCHEDULE_ID = v.SCHEDULE_ID JOIN PLACE p ON v.PLACE_ID = p.PLACE_ID WHERE s.USER_ID = ? ";
	String SHARED_FILTER = "AND s.IS_SHARED = 1 ";
	String KEYWORD_FILTER = "AND (s.TITLE LIKE ? OR p.TITLE LIKE ?) ";
	String ORDER_BY_TITLE = "ORDER BY s.TITLE ASC";
	String ORDER_BY_START_AT = "ORDER BY s.START_AT DESC";
	String DELETE_VISIT_ITEM_BY_SCHEDULE_ID = "DELETE FROM VISIT_ITEM WHERE SCHEDULE_ID = ?";
	String DELETE_MY_SCHEDULE_BY_SCHEDULE_ID = "DELETE FROM MY_SCHEDULE WHERE MY_SCHEDULE_ID = ?";
	String DELETE_VISIT_ITEMS_LIST_BY_SCHEDULE_ID = "DELETE FROM VISIT_ITEM WHERE SCHEDULE_ID = ?";
	String DELETE_MY_SCHEDULES_BY_SCHEDULE_ID = "DELETE FROM MY_SCHEDULE WHERE MY_SCHEDULE_ID = ? AND USER_ID = ?";
	String SET_MY_SCHEDULE = "UPDATE VISIT_ITEM SET VISIT_ORDER = ?, DISTANCE_TO_NEXT = ? WHERE VISIT_ITEM_ID = ?";
	String SET_VISIT_LIST = "UPDATE MY_SCHEDULE SET TITLE = ?, START_AT = ?, BUDGET_DETAILS = ?, TODO_DETAILS = ?, IS_SHARED = ? WHERE MY_SCHEDULE_ID = ? AND USER_ID = ?";
	String SET_MY_SCHEDULE_TITLE = "UPDATE MY_SCHEDULE SET TITLE = ? WHERE MY_SCHEDULE_ID = ? AND USER_ID = ?";
	String SET_TODO_DETAIL = "UPDATE MY_SCHEDULE SET TODO_DETAILS = ? WHERE MY_SCHEDULE_ID = ?";
	String GET_TODO_DETAIL = "SELECT TODO_DETAILS FROM MY_SCHEDULE WHERE MY_SCHEDULE_ID = ?";
	String SET_BUDGET_DETAIL = "UPDATE MY_SCHEDULE SET BUDGET_DETAILS = ? WHERE MY_SCHEDULE_ID = ?";
	String GET_BUDGET_DETAIL = "SELECT BUDGET_DETAILS FROM MY_SCHEDULE WHERE MY_SCHEDULE_ID = ?";
	String GET_SCHEDULE_ROUTE = "SELECT v.VISIT_ITEM_ID, v.VISIT_ORDER, p.PLACE_ID, p.TITLE FROM MY_SCHEDULE s JOIN VISIT_ITEM v ON s.MY_SCHEDULE_ID = v.SCHEDULE_ID JOIN PLACE p ON v.PLACE_ID = p.PLACE_ID WHERE s.USER_ID = ? AND s.MY_SCHEDULE_ID = ? ORDER BY v.VISIT_ORDER ASC";
	String GET_MAP_SCHEDULE = "SELECT p.TITLE, v.VISIT_ORDER, p.MAPX, p.MAPY, v.DISTANCE_TO_NEXT FROM MY_SCHEDULE s JOIN VISIT_ITEM v ON s.MY_SCHEDULE_ID = v.SCHEDULE_ID JOIN PLACE p ON v.PLACE_ID = p.PLACE_ID WHERE s.MY_SCHEDULE_ID = ? ORDER BY v.VISIT_ORDER ASC";
	String ADD_VISIT_ITEM = "INSERT INTO VISIT_ITEM (VISIT_ITEM_ID, VISIT_ORDER, SCHEDULE_TYPE, PLACE_ID, SCHEDULE_ID) VALUES (SEQ_VISIT_ITEM.NEXTVAL, ?, 'MY_SCH', ?, ?)";
	String DELETE_VISIT_ITEM_BY_ID = "DELETE FROM VISIT_ITEM WHERE VISIT_ITEM_ID = ?";
	String ADD_COMPANION = "INSERT INTO SCHEDULE_SHARE_USER (SHARE_ID, PERMISSION, MY_SCHEDULE_ID, SHARED_USER_ID) VALUES (SEQ_SCHEDULE_SHARE_USER.NEXTVAL, 'R', ?, ?)";
	String SET_COMPANION_PERMISSION = "UPDATE SCHEDULE_SHARE_USER SET PERMISSION = ? WHERE MY_SCHEDULE_ID = ? AND SHARED_USER_ID = ?";
	String GET_COMPANION_LIST = "SELECT U.USER_ID, U.NAME, U.EMAIL, SSU.PERMISSION FROM SCHEDULE_SHARE_USER SSU JOIN USERS U ON SSU.SHARED_USER_ID = U.USER_ID WHERE SSU.MY_SCHEDULE_ID = ?";
	String SHARE_TO_POST_BY_SCHEDULE_ID = "INSERT INTO SCHEDULE_POST (POST_ID, TITLE, BUDGET_DETAILS, TODO_DETAILS, IS_ANONYMOUS, VIEW_COUNT, LIKE_COUNT, POSTED_AT, USER_ID) SELECT ('P' || LPAD(SEQ_SCHEDULE_POST.NEXTVAL, 3, '0')), TITLE, BUDGET_DETAILS, TODO_DETAILS, ?, 0, 0, SYSDATE, ? FROM MY_SCHEDULE WHERE MY_SCHEDULE_ID = ?";
	String SHARE_TO_VISIT_ITEM_LIST_BY_SCHEDULE_ID = "INSERT INTO VISIT_ITEM (VISIT_ITEM_ID, VISIT_ORDER, DISTANCE_TO_NEXT, SCHEDULE_TYPE, PLACE_ID, SCHEDULE_ID) SELECT SEQ_VISIT_ITEM.NEXTVAL, VISIT_ORDER, DISTANCE_TO_NEXT, 'POST', PLACE_ID, ('P' || LPAD(SEQ_SCHEDULE_POST.CURRVAL, 3, '0')) FROM VISIT_ITEM WHERE SCHEDULE_ID = ?";
}
