package com.letsgo.place.model;

public interface PostScheduleQuery {

	
	
	String GET_POST_SCHEDULE_LIST = "SELECT p.POST_ID, p.TITLE AS POST_TITLE, p.LIKE_COUNT, p.VIEW_COUNT, p.IS_ANONYMOUS, u.NAME, v.VISIT_ITEM_ID, v.VISIT_ORDER, v.SCHEDULE_TYPE, pl.TITLE AS PLACE_TITLE, pl.addr1, pl.FIRST_IMAGE, pl.PLACE_TYPE FROM SCHEDULE_POST p JOIN VISIT_ITEM v ON p.POST_ID = v.SCHEDULE_ID JOIN PLACE pl ON v.PLACE_ID = pl.PLACE_ID JOIN USERS u ON u.user_id = p.user_id ";
	String GET_USER_POST_SCHEDULE_LIST = "SELECT p.POST_ID, p.TITLE AS POST_TITLE, p.LIKE_COUNT, p.VIEW_COUNT, p.IS_ANONYMOUS, v.VISIT_ITEM_ID, v.VISIT_ORDER, v.SCHEDULE_TYPE, pl.TITLE AS PLACE_TITLE, pl.addr1, pl.FIRST_IMAGE, pl.PLACE_TYPE FROM SCHEDULE_POST p JOIN VISIT_ITEM v ON p.POST_ID = v.SCHEDULE_ID JOIN PLACE pl ON v.PLACE_ID = pl.PLACE_ID WHERE p.USER_ID = ? ";
	
	String ORDER_BY_LIKE = "ORDER BY p.like_count ASC, p.post_id ASC, v.VISIT_ORDER ASC";
	String ORDER_BY_VIEW = "ORDER BY p.view_count ASC, p.post_id ASC, v.VISIT_ORDER ASC";
	String ORDER_BY_TITLE = "ORDER BY p.title ASC, p.post_id ASC, v.VISIT_ORDER ASC";
	String ORDER_BY_LATEST = "ORDER BY p.posted_at ASC, p.post_id ASC, v.VISIT_ORDER ASC";
	
	String SEARCH_TYPE_SCHEDULE = "WHERE p.TITLE LIKE ? ";
	String SEARCH_TYPE_PLACE = "WHERE p.POST_ID IN (SELECT v2.SCHEDULE_ID FROM VISIT_ITEM v2 JOIN PLACE pl2 ON v2.PLACE_ID = pl2.PLACE_ID WHERE pl2.TITLE LIKE ?) ";
	String SEARCH_TYPE_USER_SCHEDULE = "AND p.TITLE LIKE ? ";
	String SEARCH_TYPE_USER_PLACE = "AND p.POST_ID IN (SELECT v2.SCHEDULE_ID FROM VISIT_ITEM v2 JOIN PLACE pl2 ON v2.PLACE_ID = pl2.PLACE_ID WHERE pl2.TITLE LIKE ?) ";
	
	String DELETE_VISIT_ITEM = "DELETE FROM visit_item WHERE schedule_id = ? ";
	String DELETE_SCHEDULE_POST = "DELETE FROM schedule_post WHERE post_ID = ? ";
	
	String INCREAMENT_LIKE = "UPDATE SCHEDULE_POST SET LIKE_COUNT = LIKE_COUNT + 1 WHERE POST_ID = ? ";
}
