package com.letsgo.place.model;

public interface PostScheduleQuery {
	
	String GET_POST_SCHEDULE_LIST = "SELECT p.POST_ID, p.TITLE AS POST_TITLE, p.LIKE_COUNT, p.VIEW_COUNT, p.IS_ANONYMOUS, u.NAME, v.VISIT_ITEM_ID, v.VISIT_ORDER, v.SCHEDULE_TYPE, pl.TITLE AS PLACE_TITLE, pl.addr1, pl.FIRST_IMAGE, pl.PLACE_TYPE FROM SCHEDULE_POST p JOIN VISIT_ITEM v ON p.POST_ID = v.SCHEDULE_ID JOIN PLACE pl ON v.PLACE_ID = pl.PLACE_ID JOIN USERS u ON u.user_id = p.user_id ";
	String GET_USER_POST_SCHEDULE_LIST = "SELECT p.POST_ID, p.TITLE AS POST_TITLE, p.LIKE_COUNT, p.VIEW_COUNT, p.IS_ANONYMOUS, v.VISIT_ITEM_ID, v.VISIT_ORDER, v.SCHEDULE_TYPE, pl.TITLE AS PLACE_TITLE, pl.addr1, pl.FIRST_IMAGE, pl.PLACE_TYPE FROM SCHEDULE_POST p JOIN VISIT_ITEM v ON p.POST_ID = v.SCHEDULE_ID JOIN PLACE pl ON v.PLACE_ID = pl.PLACE_ID WHERE p.USER_ID = ? ";
	
	String ORDER_BY_LIKE = "ORDER BY p.like_count ASC, p.post_id ASC, v.VISIT_ORDER ASC";
	String ORDER_BY_VIEW = "ORDER BY p.view_count ASC, p.post_id ASC, v.VISIT_ORDER ASC";
	String ORDER_BY_TITLE = "ORDER BY p.title ASC, p.post_id ASC, v.VISIT_ORDER ASC";
	String ORDER_BY_LATEST = "ORDER BY p.posted_at ASC, p.post_id ASC, v.VISIT_ORDER ASC";
	String ORDER_BY_DEFAULT = "ORDER BY p.posted_at ASC, p.post_id ASC, v.VISIT_ORDER ASC";
	
	String SEARCH_TYPE_FILTER = "WHERE p.TITLE LIKE ? OR pl.TITLE LIKE ? ";
	String SEARCH_TYPE_USER_FILTER = "AND (p.TITLE LIKE ? OR pl.TITLE LIKE ?) ";
	
	String DELETE_VISIT_ITEM = "DELETE FROM visit_item WHERE schedule_id = ? ";
	String DELETE_SCHEDULE_POST = "DELETE FROM schedule_post WHERE post_ID = ? ";
	
	String GET_BUDGET_DETAIL = "SELECT BUDGET_DETAILS FROM SCHEDULE_POST WHERE POST_ID = ? ";
	String GET_TODO_DETAIL = "SELECT TODO_DETAILS FROM SCHEDULE_POST WHERE POST_ID = ?" ;
	String GET_SCHEDULE_ROUTE = "SELECT v.VISIT_ITEM_ID, v.VISIT_ORDER, p.PLACE_ID, p.TITLE FROM SCHEDULE_POST sp JOIN VISIT_ITEM v ON sp.POST_ID = v.SCHEDULE_ID JOIN PLACE p ON v.PLACE_ID = p.PLACE_ID WHERE sp.POST_ID = ? ORDER BY v.VISIT_ORDER ASC ";
	String GET_MAP_SCHEDULE = "SELECT p.TITLE, v.VISIT_ORDER, p.MAPX, p.MAPY, v.DISTANCE_TO_NEXT FROM SCHEDULE_POST sp JOIN VISIT_ITEM v ON sp.POST_ID = v.SCHEDULE_ID JOIN PLACE p ON v.PLACE_ID = p.PLACE_ID WHERE sp.POST_ID = ? ORDER BY v.VISIT_ORDER ASC ";
	String GET_SCHEDULE_TITLE = "SELECT TITLE FROM SCHEDULE_POST WHERE POST_ID = ?";
	
	String GET_LIKE_COUNT = "SELECT LIKE_COUNT FROM SCHEDULE_POST WHERE POST_ID = ? ";
	String GET_VIEW_COUNT = "SELECT VIEW_COUNT FROM SCHEDULE_POST WHERE POST_ID = ? ";
	String PLUS_LIKE_COUNT = "UPDATE SCHEDULE_POST SET LIKE_COUNT = LIKE_COUNT + 1 WHERE POST_ID = ? ";
	String PLUS_VIEW_COUNT = "UPDATE SCHEDULE_POST SET VIEW_COUNT = VIEW_COUNT + 1 WHERE POST_ID = ? ";

	String GET_USER_ID = "SELECT USER_ID FROM SCHEDULE_POST WHERE POST_ID = ? ";
}

