package com.letsgo.place.model;

public interface UserQury {
	String LOGIN_SQL = "SELECT NAME, EMAIL FROM USERS WHERE USER_ID = ? AND PASSWORD = ?";
	String SIGNUP_SQL = "INSERT INTO USERS (USER_ID, EMAIL, NAME, PASSWORD) VALUES (?,?,?,?)";
	String IDCHECK_SQL = "SELECT 1 FROM USERS WHERE USER_ID = ?";
	String UPDATE_PASSWORD_BY_ID_EMAIL_SQL = "UPDATE USERS SET PASSWORD = ? WHERE USER_ID = ? AND EMAIL = ?";
	String FIND_USER_ID_BY_NAME_EMAIL_SQL = "SELECT USER_ID FROM USERS WHERE NAME = ? AND EMAIL = ?";

}
